export const defaultFormState = {
  ma_hang: '',
  ma_vach: '',
  ten_thuoc: '',
  ten_viet_tat: '',
  nhom_hang_id: null,
  gia_von: 0,
  gia_ban: 0,
  so_dang_ky: '',
  hoat_chat: '',
  ham_luong: '',
  drugusage_id: null,
  manufacturer_id: null,
  quy_cach_dong_goi: '',
  nuoc_san_xuat: '',
  ton_kho: '0',
  ton_thap_nhat: '',
  ton_cao_nhat: '',
  position_id: null,
  trong_luong: 0,
  don_vi_tinh: '',
  ban_truc_tiep: false,
  mo_ta: '',
  image: null
}
